site_name: Theme.Park Docs
site_description: Here you can find installation and setup details for all the themes in the GilbN/theme.park repo
site_author: GilbN
site_url: https://gilbn.github.io/tp-docs/

repo_url: https://github.com/GilbN/theme.park
repo_name: GilbN/theme.park

plugins:
  - search
  - git-revision-date-localized
  - awesome-pages
  - macros

markdown_extensions:
  - admonition
  - attr_list
  - codehilite
  - footnotes
  - lightgallery
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:pymdownx.emoji.twemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Setup: /setup
  - Themes:
      Sonarr: themes/sonarr.md
      Radarr: themes/radarr.md
      Lidarr: themes/lidarr.md
      Readarr: themes/readarr.md
      Bazarr: themes/bazarr.md
      Organizr: themes/organizr.md 
  - Addons:
      Sonarr: themes/addons/sonarr/index.md
      Radarr: themes/addons/radarr/index.md
      Bazarr: themes/addons/bazarr/index.md
      Organizr: themes/addons/organizr/index.md
      Unraid:
        Alien: themes/addons/unraid/login-page/alien/index.md
        Fallout: themes/addons/unraid/login-page/fallout/index.md
        Retro Terminal: themes/addons/unraid/login-page/retro-terminal/index.md

  - Custom Themes: /themes/custom

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.expand
  language: en
  font:
    text: Roboto
    code: Roboto Mono
  favicon: site_assets/favicon.ico
  logo: site_assets/logo.png

extra:
  homepage: https://github.com/GilbN/theme.park
  addons:
    sonarr:
      4K Logo: 
        path: /themes/addons/sonarr
    radarr:
      4K Logo:
        path: /themes/addons/radarr
    bazarr:
      4K Logo:
        path: /themes/addons/bazarr
    organizr:
      Organizr Glass:
        path: /themes/addons/organizr
    unraid:
      Alien:
        path: /themes/addons/unraid/login-page/alien
      Fallout:
        path: /themes/addons/unraid/login-page/fallout
      Retro Terminal:
        path: /themes/addons/unraid/login-page/retro-terminal
